# Generated by Django 4.2.3 on 2023-09-02 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_id"),
        ("users", "0002_user_completed_lessons"),
    ]

    operations = []
