# Generated by Django 4.1.13 on 2023-12-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_picture"),
        ("users", "0007_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="completed_lessons",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="completed_by",
                to="courses.completedlesson",
            ),
        ),
    ]
