# Generated by Django 4.2.6 on 2023-11-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_name']},
        ),
    ]
