# Generated by Django 4.2.3 on 2023-08-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_completedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedlesson',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='completedlesson',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.RemoveField(
            model_name='completedlesson',
            name='user',
        ),
    ]
