# Generated by Django 4.2.6 on 2023-11-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_name']},
        ),
        migrations.AddField(
            model_name='completedlesson',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment'),
            preserve_default=False,
        ),
    ]
