# Generated by Django 4.2.3 on 2023-11-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_chapter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="course_pictures"),
        ),
    ]
