# Generated by Django 4.2.3 on 2023-10-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_completedlesson_unique_together_and_more'),
        ('courses', '0004_chapter_chapter_quiz'),
    ]

    operations = [
    ]
