# Generated by Django 4.2.3 on 2023-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_completedlesson_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="course_pictures"),
        ),
    ]
