# Generated by Django 4.2.3 on 2023-09-02 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_chapter_chapter_quiz"),
        ("courses", "0005_alter_completedlesson_unique_together_and_more"),
    ]

    operations = []
