# Generated by Django 4.2.6 on 2023-11-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_options_lesson_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_name']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
    ]
