# Generated by Django 4.2.3 on 2023-12-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_completedlesson_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedlesson',
            name='enrollment',
        ),
    ]
