# Generated by Django 4.2.3 on 2023-09-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_merge_20230902_2254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedlesson",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
