# Generated by Django 4.2.3 on 2023-12-07 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_completedlesson_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedlesson',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment'),
        ),
    ]
