# Generated by Django 4.2.3 on 2023-09-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0003_videolesson_videoprogress"),
        ("courses", "0007_alter_completedlesson_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="resources.videolesson",
            ),
        ),
    ]
