# Generated by Django 4.2.3 on 2023-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_certificate_issuer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="word_file",
            field=models.FileField(
                blank=True, null=True, upload_to="lesson_word_files/"
            ),
        ),
    ]
