# Generated by Django 4.2.3 on 2023-11-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_alter_lesson_lesson_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="word_file",
            field=models.FileField(blank=True, null=True, upload_to="word_files/"),
        ),
    ]
