# Generated by Django 4.2.3 on 2023-11-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_alter_lesson_word_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="word_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
