# Generated by Django 4.2.3 on 2023-11-12 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quizsubmission",
            unique_together={("student", "quiz")},
        ),
    ]
