# Generated by Django 4.2.6 on 2023-11-16 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0003_alter_quizsubmission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='completed_quizzes',
            field=models.ManyToManyField(blank=True, related_name='completed_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
