# Generated by Django 4.2.3 on 2023-08-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_chapter_lesson"),
        ("assignments", "0005_quiz_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="chapter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.chapter",
            ),
            preserve_default=False,
        ),
    ]
