# Generated by Django 4.2.3 on 2023-08-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_chapter_lesson"),
        ("assignments", "0006_quiz_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_quizzes",
                to="courses.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="quiz_title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
