# Generated by Django 4.2.3 on 2023-08-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0008_alter_assignment_id_alter_choice_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choice",
                to="assignments.question",
            ),
        ),
    ]
