# Generated by Django 4.2.3 on 2023-11-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="videoprogress",
            name="video_lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resources.videolesson"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
    ]
