# Generated by Django 4.2.3 on 2023-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0003_videolesson_videoprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videolesson",
            name="video_url",
        ),
        migrations.AddField(
            model_name="videolesson",
            name="video_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
