# Generated by Django 4.2.3 on 2023-09-18 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0004_remove_videolesson_video_url_videolesson_video_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videolesson",
            old_name="video_id",
            new_name="video_lesson_id",
        ),
    ]
